package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// GenerateServers generates HTTP servers for all services in the file
func (g *generator) GenerateServers(file *protogen.File) (err error) {
	g.gf.P("// Code generated by protoc-gen-httpgo. DO NOT EDIT.")
	g.gf.P("// source: ", file.Desc.Path())
	g.gf.P()
	g.gf.P("package ", file.GoPackageName)
	g.gf.P()
	g.gf.P("type HandlerFunc = func(", g.serverInput, ") (", g.serverOutput, ")")
	g.gf.P("type MiddlewareFunc = func(", g.serverInput, ", handler HandlerFunc) (", g.serverOutput, ")")
	g.gf.P()

	for _, service := range g.services {
		g.genServiceInterface(service)
		if *g.cfg.Only == onlyClient {
			continue
		}
		if err = g.genServiceServer(service); err != nil {
			return err
		}
	}
	if *g.cfg.Only == onlyClient {
		return nil
	}

	g.genChainServerMiddlewares()
	g.genServerStream()
	return nil
}

// genServiceInterface generates interface for HTTP server and client
func (g *generator) genServiceInterface(service serviceParams) {
	g.gf.P("type ", service.name, "HTTPGoService interface {")
	for _, method := range service.methods {
		if method.streaming {
			g.gf.P(
				"	", method.name, "(*", method.inputMsgName, ", ",
				grpcPackage.Ident("ServerStreamingServer"), "[", method.outputMsgName, "]) error",
			)
		} else {
			g.gf.P(
				"	", method.name, "(", contextPackage.Ident("Context"), ", *", method.inputMsgName, ") ",
				"(*", method.outputMsgName, ", error)",
			)
		}
	}
	g.gf.P("}")
}

// genServiceServer generates HTTP server for serviceParams
func (g *generator) genServiceServer(service serviceParams) (err error) {
	g.gf.P("func Register", service.name, "HTTPGoServer(")
	g.gf.P("	_ ", contextPackage.Ident("Context"), ",")
	g.gf.P("	r *", g.lib.Ident("ServeMux"), ",")
	g.gf.P("	h ", service.name, "HTTPGoService,")
	g.gf.P("	middlewares []MiddlewareFunc,")
	g.gf.P(") error {")
	g.gf.P("	var middleware = chainServerMiddlewares", g.filename, "(middlewares)")
	for _, method := range service.methods {
		if err = g.genMethodDeclaration(service.name, method); err != nil {
			return err
		}
	}
	g.gf.P("	return nil")
	g.gf.P("}")
	g.gf.P()

	for _, method := range service.methods {
		if err = g.genBuildRequestMethod(service.name, method); err != nil {
			return err
		}
	}
	g.gf.P()
	return nil
}

// genMethodDeclaration generates binding route with handler
func (g *generator) genMethodDeclaration(serviceName string, method methodParams) (err error) {
	g.gf.P(method.comment)

	g.gf.P("r.HandleFunc( \"", method.httpMethodName, " ", method.uri.protoURI, "\", func(w ", g.lib.Ident("ResponseWriter"), ", r *", g.lib.Ident("Request"), ") { ")
	if !method.streaming {
		g.gf.P("	w.Header().Set(\"Content-Type\", \"application/json\")")
	}
	g.gf.P("	input, err := build", g.getBuildMethodInputName(serviceName, method), "(r)")
	g.gf.P("	if err != nil {")
	g.gf.P("		w.Header().Set(\"Content-Type\", \"application/json\")")
	g.gf.P("		w.WriteHeader(", g.lib.Ident("StatusBadRequest"), ")")
	// can't use protojson on inline structure
	g.gf.P("		respJson, _ := ", jsonPackage.Ident("Marshal"), "(struct{ Error string }{Error: err.Error()})")
	g.gf.P("		_, _ = w.Write(respJson)")
	g.gf.P("		return")
	g.gf.P("	}")
	g.gf.P("	ctx := r.Context()")
	g.gf.P("	ctx = ", contextPackage.Ident("WithValue"), "(ctx, \"http_writer\", w)")
	g.gf.P("	ctx = ", contextPackage.Ident("WithValue"), "(ctx, \"http_request\", r)")
	g.gf.P("	ctx = ", contextPackage.Ident("WithValue"), "(ctx, \"proto_service\", \""+serviceName+"\")")
	g.gf.P("	ctx = ", contextPackage.Ident("WithValue"), "(ctx, \"proto_method\", \""+method.name+"\")")
	if method.streaming {
		g.gf.P("	handler := func(", g.serverInput, ") error {")
		g.gf.P("		stream := NewHTTPServerStream[", method.outputMsgName, "](w, r)")
		g.gf.P("		return h.", method.name, "(input, stream)")
		g.gf.P("	}")
		g.gf.P("	err = handler(ctx, input)")
		g.gf.P("	if err != nil {")
		g.gf.P(`		w.Header().Set("Content-Type", "application/json")`)
		g.gf.P("		w.WriteHeader(", g.lib.Ident("StatusBadRequest"), ")")
		g.gf.P("		respJson, _ := ", jsonPackage.Ident("Marshal"), "(struct{ Error error }{Error: err})")
		g.gf.P("		_, _ = w.Write(respJson)")
		g.gf.P("		return")
		g.gf.P("	}")
	} else {
		g.gf.P("	handler := func(", g.serverInput, ") (", g.serverOutput, ") {")
		g.gf.P("		return h.", method.name, "(ctx, input)")
		g.gf.P("	}")
		g.gf.P("	var resp any")
		g.gf.P("	if middleware == nil {")
		// errors should be dealt with in handler or middlewares
		g.gf.P("		resp, _ = handler(ctx, input)")
		g.gf.P("	} else {")
		g.gf.P("		resp, _ = middleware(ctx, input, handler)")
		g.gf.P("	}")
		g.gf.P("	if resp == nil {")
		g.gf.P("		return")
		g.gf.P("	}")

		if method.rule != nil && method.rule.ResponseBody != "" {
			respField, ok := method.outputFields[method.rule.ResponseBody]
			if !ok {
				return fmt.Errorf("field %s not found in struct %s for method %s", method.rule.ResponseBody, method.outputMsgName.String(), method.name)
			}
			g.gf.P("if typedResp, ok := resp.(*", method.inputMsgName, "); ok {")
			g.genMarshalServerResponse("typedResp." + respField.goName)
			g.gf.P("} else {")
			g.genMarshalServerResponse("resp")
			g.gf.P("}")

		} else {
			g.genMarshalServerResponse("resp")
		}
	}
	g.gf.P("})")
	g.gf.P()
	if method.rule != nil && len(method.rule.AdditionalBindings) > 0 {
		// this will duplicate whole method. can be optimized
		for _, binding := range method.rule.AdditionalBindings {
			copiedMethod := method.Copy()
			copiedMethod.httpMethodName, copiedMethod.uri.protoURI = getRuleMethodAndURI(binding)
			copiedMethod.uri.parseURI()
			copiedMethod.rule.AdditionalBindings = nil
			if err = g.genMethodDeclaration(serviceName, copiedMethod); err != nil {
				return err
			}
		}
	}
	return nil
}

func (g *generator) genMarshalServerResponse(source string) {
	// we can't assert interface if source is a field
	if *g.cfg.Marshaller == marshallerProtoJSON && source == "resp" {
		g.gf.P("	respJson, _ := ", g.marshaller.Ident("Marshal"), "(", source, ".(", protoPackage.Ident("Message"), "))")
	} else {
		g.gf.P("	respJson, _ := ", g.marshaller.Ident("Marshal"), "(", source, ")")
	}
	g.gf.P("	if respJson != nil {")
	g.gf.P("		_, _ = w.Write(respJson)")
	g.gf.P("	}")

}

// getBuildMethodInputName creates name for function that builds method request
func (g *generator) getBuildMethodInputName(serviceName string, method methodParams) string {
	methodName := g.filename + serviceName + method.name + method.inputMsgName.GoName
	return strings.NewReplacer(".", "", "-", "", "_", "").Replace(methodName)
}

// genBuildRequestMethod generates method that build request struct
func (g *generator) genBuildRequestMethod(serviceName string, method methodParams) (err error) {
	g.gf.P("func build", g.getBuildMethodInputName(serviceName, method), "(r *", g.lib.Ident("Request"), ") (arg *", method.inputMsgName, ", err error) {")
	g.gf.P("	arg = &", method.inputMsgName, "{}")
	if method.withFiles {
		if err = g.genMultipartRequestServer(method); err != nil {
			return err
		}
	} else if method.HasBody() {
		if err = g.genUnmarshalRequestStruct(method); err != nil {
			return err
		}
	}
	if err = g.genServerMethodQueryParams(method); err != nil {
		return err
	}

	var allGeneratedFields = make(map[string]struct{})
	if err = g.genMethodPathArguments(method, allGeneratedFields); err != nil {
		return err
	}
	if method.rule != nil && len(method.rule.AdditionalBindings) > 0 {
		for _, binding := range method.rule.AdditionalBindings {
			copiedMethod := method.Copy()
			copiedMethod.httpMethodName, copiedMethod.uri.protoURI = getRuleMethodAndURI(binding)
			copiedMethod.uri.parseURI()
			if err = g.genMethodPathArguments(copiedMethod, allGeneratedFields); err != nil {
				return err
			}
		}
	}

	g.gf.P("	return arg, err")
	g.gf.P("}")
	g.gf.P()
	return nil
}

func (g *generator) genMethodPathArguments(method methodParams, generatedFields map[string]struct{}) (err error) {
	for _, fieldName := range method.uri.argList {
		if _, ok := generatedFields[fieldName]; ok {
			continue
		}
		if f, ok := method.inputFields[fieldName]; ok {
			if err = g.genBuildPathArgument(f, method.uri.args[fieldName]); err != nil {
				return err
			}
			generatedFields[fieldName] = struct{}{}
		} else {
			return fmt.Errorf("path argument %s found in uri, but not found in method %s argument fields", fieldName, method.name)
		}
	}
	return nil
}

func (g *generator) genServerMethodQueryParams(method methodParams) (err error) {
	if len(method.inputFieldList) == 0 {
		return nil
	}
	g.gf.P("for key, values := range r.URL.Query() {")
	g.gf.P("	for _, value := range values {")
	g.gf.P("	switch key {")
	for _, f := range method.inputFieldList {
		if err = g.genQueryArgCheck(method.inputFields[f]); err != nil {
			return err
		}
	}
	g.gf.P("	default:")
	g.gf.P("		return nil, ", fmtPackage.Ident("Errorf"), "(\"unknown query parameter %s with value '%s'\", key, value)")
	g.gf.P("	}")
	g.gf.P("}")
	g.gf.P("}")
	return nil
}

// genBuildPathArgument generates code for request argument
func (g *generator) genBuildPathArgument(
	f field,
	uriArg methodURIArg,
) (err error) {
	g.gf.P("	", f.goName, "Str := r.PathValue(\"", f.protoName, "\")")
	g.gf.P("	if len(", f.goName, "Str) != 0 {")
	if f.cardinality == protoreflect.Repeated {
		if err = g.genRepeatedPathArgCheck(f); err != nil {
			return err
		}
		g.gf.P("	}")
		g.gf.P()
		return nil
	}
	switch f.kind {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind, protoreflect.Sfixed32Kind, protoreflect.Fixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind, protoreflect.Uint64Kind, protoreflect.Fixed64Kind,
		protoreflect.DoubleKind, protoreflect.FloatKind, protoreflect.StringKind, protoreflect.BytesKind, protoreflect.BoolKind,
		protoreflect.EnumKind:
		if err = g.genFieldConvertor(f, f.goName+"Str", "arg."+f.goName, false, "nil, ", false); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unsupported type %s for path variable", f.kind.String())
	}
	if uriArg.DestinationTpl != "" {
		g.gf.P("arg.", f.goName, " = ", fmtPackage.Ident("Sprintf"), "(\"", uriArg.DestinationTpl, "\", arg.", f.goName, ")")
	}
	g.gf.P("	}")
	g.gf.P()
	return nil
}

func (g *generator) genRepeatedPathArgCheck(f field) (err error) {
	switch f.kind {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind, protoreflect.Sfixed32Kind, protoreflect.Fixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind, protoreflect.Uint64Kind, protoreflect.Fixed64Kind,
		protoreflect.DoubleKind, protoreflect.FloatKind, protoreflect.BoolKind, protoreflect.EnumKind:
		g.gf.P(f.goName, "Strs := ", stringsPackage.Ident("Split"), "(", f.goName, "Str, \""+pathRepeatedArgDelimiter+"\")")
		// allocate space and override values if it was passed in a body or other way
		g.gf.P("arg.", f.goName, " = make([]", getFieldConversionFuncName(f), ", 0, len(", f.goName, "Strs))")
		g.gf.P("for _, str := range ", f.goName, "Strs {")
		if err = g.genFieldConvertor(f, "str", "arg."+f.goName, true, "nil, ", false); err != nil {
			return err
		}
		g.gf.P("}")
	case protoreflect.StringKind:
		source := g.gf.QualifiedGoIdent(stringsPackage.Ident("Split")) + "(" + f.goName + "Str, \"" + pathRepeatedArgDelimiter + "\")"
		if err = g.genFieldConvertor(f, source, "arg."+f.goName, false, "", false); err != nil {
			return err
		}
	case protoreflect.BytesKind:
		g.gf.P(f.goName, "Strs := ", stringsPackage.Ident("Split"), "(", f.goName, "Str, \""+pathRepeatedArgDelimiter+"\")")
		// allocate space and override values if it was passed in a body or other way
		g.gf.P("arg.", f.goName, " = make([][]byte, 0, len(", f.goName, "Strs))")
		g.gf.P("for _, str := range ", f.goName, "Strs {")
		if err = g.genFieldConvertor(f, "str", "arg."+f.goName, true, "", false); err != nil {
			return err
		}
		g.gf.P("}")
	default:
		g.gf.P("err = ", fmtPackage.Ident("Errorf"), "(\"unsupported type repeated ", f.kind.String(), " for path argument ", f.goName, "\")")
		g.gf.P("return nil, err")
	}
	return nil
}

// genChainServerMiddlewares generates server middleware chain functions
func (g *generator) genChainServerMiddlewares() {
	g.gf.P("func chainServerMiddlewares", g.filename, "(")
	g.gf.P("	middlewares []MiddlewareFunc,")
	g.gf.P(") func(", g.serverInput, ", handler HandlerFunc) (", g.serverOutput, ") {")
	g.gf.P("	switch len(middlewares) {")
	g.gf.P("	case 0:")
	g.gf.P("		return nil")
	g.gf.P("	case 1:")
	g.gf.P("		return middlewares[0]")
	g.gf.P("	default:")
	g.gf.P("		return func(", g.serverInput, ", handler HandlerFunc) (", g.serverOutput, ") {")
	g.gf.P("			return middlewares[0](ctx, req, getChainServerMiddlewareHandler", g.filename, "(middlewares, 0, handler))")
	g.gf.P("		}")
	g.gf.P("	}")
	g.gf.P("}")
	g.gf.P()
	g.gf.P("func getChainServerMiddlewareHandler", g.filename, "(")
	g.gf.P("	middlewares []MiddlewareFunc,")
	g.gf.P("	curr int,")
	g.gf.P("	finalHandler HandlerFunc,")
	g.gf.P(") func(", g.serverInput, ") (", g.serverOutput, ") {")
	g.gf.P("	if curr == len(middlewares)-1 {")
	g.gf.P("		return finalHandler")
	g.gf.P("	}")
	g.gf.P("	return func(", g.serverInput, ") (", g.serverOutput, ") {")
	g.gf.P("		return middlewares[curr+1](ctx, req, getChainServerMiddlewareHandler", g.filename, "(middlewares, curr+1, finalHandler))")
	g.gf.P("	}")
	g.gf.P("}")
}

// genUnmarshalRequestStruct generates unmarshalling from []byte to struct for request
func (g *generator) genUnmarshalRequestStruct(method methodParams) (err error) {
	g.gf.P("	var body []byte")
	g.gf.P("	if body, err = ", ioPackage.Ident("ReadAll"), "(r.Body); err != nil {")
	g.gf.P("		return nil, err")
	g.gf.P("	}")
	g.gf.P("	_ = r.Body.Close()")
	g.gf.P("	if len(body) > 0 { ")
	destination := "arg"
	if method.rule != nil && method.rule.Body != "" && method.rule.Body != "*" {
		f, ok := method.inputFields[method.rule.Body]
		if !ok {
			return fmt.Errorf("field %s set as body value, but not found in method %s argument fields", method.rule.Body, method.name)
		}
		destination = "arg." + f.goName
		g.gf.P("	", destination, " = &", f.structTypeIdent, "{}")
	}
	g.gf.P("		if err = ", g.marshaller.Ident("Unmarshal"), "(body, ", destination, "); err != nil {")
	g.gf.P("			return nil, err")
	g.gf.P("		}")
	g.gf.P("	}")
	return nil
}

func (g *generator) genMultipartRequestServer(method methodParams) (err error) {
	g.gf.P("if err = r.ParseMultipartForm(32 << 20); err != nil {")
	g.gf.P("	return nil, err")
	g.gf.P("}")

	for _, fieldName := range method.inputFieldList {
		f := method.inputFields[fieldName]
		if f.isFile {
			g.genMultipartServerRequestField(f)
			continue
		}
		g.gf.P("if values := r.Form[\"", f.protoName, "\"]; len(values) > 0 {")
		switch {
		case f.cardinality == protoreflect.Repeated && f.kind == protoreflect.StringKind:
			g.gf.P("	arg."+f.goName, " = append(arg."+f.goName, ", values...)")
		case f.cardinality == protoreflect.Repeated:
			g.gf.P("	for _, value := range values {")
			if err = g.genFieldConvertor(f, "value", "arg."+f.goName, true, "nil, ", false); err != nil {
				return err
			}
			g.gf.P("	}")
		default:
			if err = g.genFieldConvertor(f, "values[0]", "arg."+f.goName, false, "nil, ", false); err != nil {
				return err
			}
		}
		g.gf.P("}")
	}
	return nil
}

func (g *generator) genMultipartServerRequestField(methodField field) {
	g.gf.P("f, fh, err := r.FormFile(\"", methodField.protoName, "\")")
	g.gf.P("if err == nil && !", errorsPackage.Ident("Is"), "(err, ", httpPackage.Ident("ErrMissingFile"), ") {")
	g.gf.P("	arg.", methodField.goName, " = &", methodField.fileStructIdent(), "{")
	g.gf.P("		File:    make([]byte, fh.Size),")
	g.gf.P("		Name:    fh.Filename,")
	g.gf.P("		Headers: make(map[string]string, len(fh.Header)),")
	g.gf.P("	}")
	g.gf.P("	for key, value := range fh.Header {")
	g.gf.P("		arg.", methodField.goName, ".Headers[key] = value[0]")
	g.gf.P("	}")
	g.gf.P("	_, err = f.Read(arg.", methodField.goName, ".File)")
	g.gf.P("	if err != nil {")
	g.gf.P("		return nil, fmt.Errorf(\"failed to read file: ", methodField.protoName, ": %w\", err)")
	g.gf.P("	}")
	g.gf.P("}")
}

func (g *generator) genQueryArgCheck(f field) (err error) {
	if f.cardinality == protoreflect.Repeated {
		g.gf.P("	case \"", f.protoName, "[]\":")
	} else {
		g.gf.P("	case \"", f.protoName, "\":")
	}

	nakedReturn := false
	switch f.kind {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind, protoreflect.Sfixed32Kind, protoreflect.Fixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind, protoreflect.Uint64Kind, protoreflect.Fixed64Kind,
		protoreflect.DoubleKind, protoreflect.FloatKind, protoreflect.StringKind, protoreflect.BytesKind, protoreflect.BoolKind,
		protoreflect.EnumKind:
		if err = g.genFieldConvertor(
			f,
			"value",
			"arg."+f.goName,
			f.cardinality == protoreflect.Repeated,
			"nil, ",
			nakedReturn,
		); err != nil {
			return err
		}
	default:
		g.gf.P("	return nil, ", fmtPackage.Ident("Errorf"), "(\"unsupported type "+f.kind.String()+" for query argument "+f.protoName+"\")")
	}

	if f.kind == protoreflect.MessageKind && !f.isFile && f.cardinality != protoreflect.Repeated {
		for _, sf := range f.structFields {
			if sf.Desc.Cardinality() == protoreflect.Repeated ||
				sf.Desc.HasOptionalKeyword() || // todo add optional sub fields
				sf.Desc.Kind() == protoreflect.MessageKind { // for now support first sublevel fields only
				continue
			}
			g.gf.P("	case \"", f.protoName, ".", sf.Desc.TextName(), "\":")
			g.gf.P("		if arg.", f.goName, " == nil {")
			g.gf.P("			arg.", f.goName, " = &", f.structTypeIdent, "{}")
			g.gf.P("		}")
			if err = g.genFieldConvertor(
				convertField(sf),
				"value",
				"arg."+f.goName+"."+sf.GoName,
				f.cardinality == protoreflect.Repeated,
				"nil, ",
				nakedReturn,
			); err != nil {
				return err
			}
		}
	}
	return nil
}

func (g *generator) genServerStream() (err error) {
	g.gf.P()
	g.gf.P("// httpServerStream implements grpc.ServerStreamingServer for HTTP.")
	g.gf.P("type httpServerStream[Res any] struct {")
	g.gf.P("	w ", httpPackage.Ident("ResponseWriter"))
	g.gf.P("	r *", httpPackage.Ident("Request"))
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func NewHTTPServerStream[Res any](w ", httpPackage.Ident("ResponseWriter"), ", r *", httpPackage.Ident("Request"), ") ", grpcPackage.Ident("ServerStreamingServer"), "[Res] {")
	g.gf.P(`	w.Header().Set("Content-Type", "application/x-ndjson")`)
	g.gf.P(`	w.Header().Set("Transfer-Encoding", "chunked")`)
	g.gf.P("	return &httpServerStream[Res]{w: w, r: r}")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) Send(m *Res) error {")
	g.gf.P("	msg, ok := any(m).(proto.Message)")
	g.gf.P("	if !ok {")
	g.gf.P("		return ", grpcStatusPackage.Ident("Error"), "(", grpcCodesPackage.Ident("Internal"), ", ", fmtPackage.Ident("Sprintf"), "(\"message type %T does not implement proto.Message\", m))")
	g.gf.P("	}")
	g.gf.P("	b, err := ", g.marshaller.Ident("Marshal"), "(msg)")
	g.gf.P("	if err != nil {")
	g.gf.P("		return ", grpcStatusPackage.Ident("Error"), "(", grpcCodesPackage.Ident("Internal"), ", err.Error())")
	g.gf.P("	}")
	g.gf.P("	if _, err := s.w.Write(b); err != nil {")
	g.gf.P("		return err")
	g.gf.P("	}")
	g.gf.P(`	if _, err := s.w.Write([]byte("\n")); err != nil {`)
	g.gf.P("		return err")
	g.gf.P("	}")
	g.gf.P("	if flusher, ok := s.w.(", httpPackage.Ident("Flusher"), "); ok {")
	g.gf.P("		flusher.Flush()")
	g.gf.P("	}")
	g.gf.P("	return nil")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) Context() ", contextPackage.Ident("Context"), " {")
	g.gf.P("	return s.r.Context()")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) SetHeader(md ", grpcMetadataPackage.Ident("MD"), ") error {")
	g.gf.P("	for k, v := range md {")
	g.gf.P("		for _, val := range v {")
	g.gf.P("			s.w.Header().Add(k, val)")
	g.gf.P("		}")
	g.gf.P("	}")
	g.gf.P("	return nil")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) SendHeader(md ", grpcMetadataPackage.Ident("MD"), ") error {")
	g.gf.P("	_ = s.SetHeader(md)")
	g.gf.P("	s.w.WriteHeader(", httpPackage.Ident("StatusOK"), ")")
	g.gf.P("	return nil")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) SetTrailer(md ", grpcMetadataPackage.Ident("MD"), ") {")
	g.gf.P("	// Trailers are not easily supported in standard HTTP/1.1 streaming without trailers header.")
	g.gf.P("	// For simplicity, we skip them or can add them as headers if SendHeader hasn't been called.")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) SendMsg(m any) error {")
	g.gf.P("	return s.Send(m.(*Res))")
	g.gf.P("}")
	g.gf.P("")
	g.gf.P("func (s *httpServerStream[Res]) RecvMsg(m any) error {")
	g.gf.P("	return nil")
	g.gf.P("}")
	return nil
}
